jobs:
- name: nessus-manager-boshrelease
  plan:
  - aggregate:
    - get: release-git-repo
      trigger: true
    - get: pipeline-tasks
    - get: final-builds-dir-tarball
    - get: releases-dir-tarball
  - task: finalize-release
    file: pipeline-tasks/finalize-bosh-release.yml
    config:
      params:
        PRIVATE_YML_CONTENT: {{private-yml}}
  - aggregate:
    - put: release-tarball
      params:
        file: finalized-release/nessus-manager-*.tgz
    - put: final-builds-dir-tarball
      params:
        file: finalized-release/final-builds-dir-nessus-manager.tgz
    - put: releases-dir-tarball
      params:
        file: finalized-release/releases-dir-nessus-manager.tgz

resources:
- name: release-git-repo
  type: git
  source:
    uri: {{release-git-url}}
    branch: {{release-git-branch}}
- name: pipeline-tasks
  type: git
  source:
    uri: {{pipeline-tasks-git-url}}
    branch: {{pipeline-tasks-git-branch}}
- name: release-tarball
  type: s3
  source:
    bucket: {{s3-bosh-releases-bucket}}
    regexp: nessus-manager-(.*).tgz
    access_key_id: {{s3-bosh-releases-access-key-id}}
    secret_access_key: {{s3-bosh-releases-secret-access-key}}
    region_name: {{region}}
    server_side_encryption: AES256
- name: final-builds-dir-tarball
  type: s3
  source:
    bucket: {{s3-bosh-releases-bucket}}
    versioned_file: final-builds-dir-nessus-manager.tgz
    access_key_id: {{s3-bosh-releases-access-key-id}}
    secret_access_key: {{s3-bosh-releases-secret-access-key}}
    region_name: {{region}}
    server_side_encryption: AES256
- name: releases-dir-tarball
  type: s3
  source:
    bucket: {{s3-bosh-releases-bucket}}
    versioned_file: releases-dir-nessus-manager.tgz
    access_key_id: {{s3-bosh-releases-access-key-id}}
    secret_access_key: {{s3-bosh-releases-secret-access-key}}
    region_name: {{region}}
    server_side_encryption: AES256
